# Jekyll
exclude: nbproject, README.md, manifest.yml, rakefile.rb, Gemfile, Gemfile.lock, update.sh
permalink:   /:year/:month/:title
url:         http://zhuao.github.io

safe:        false
auto:        false

future:      false
pygments:    true
markdown:    rdiscount
